# Generated by Django 5.1.4 on 2025-01-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyzePRRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_url", models.CharField(max_length=450)),
                ("pr_number", models.IntegerField()),
                (
                    "github_token",
                    models.CharField(blank=True, max_length=650, null=True),
                ),
            ],
        ),
    ]
